services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///./meeting_minutes.db
      - PYTHONPATH=/app
    working_dir: /app # 追加
    command: tail -f /dev/null
